import {MAX_WATCHLIST_SYMBOLS} from './lib/watchlist-limits.js';
// Only the composition root supplies process.env. Modules receive explicit values.
export const DEFAULTS=Object.freeze({
  HOST:'127.0.0.1',PORT:8567,SYMBOLS:'QQQ,SPY',PUBLIC_ORIGIN:'',STATS_TOKEN:'',LLM_API_KEY:'',LLM_KEY_STORE_PATH:'./state/api-keys.json',API_V1_DEPRECATION_AT:'',API_V1_SUNSET_AT:'',
  REALTIME_SNAPSHOTS:'1',PUBLIC_SOURCE_REDUNDANCY:'1',RECOVERY_PATH:'./state/quotes.json',FX_MODE:'reference',
  POLL_MS:1000,POLL_PRIMARY:'sina',CACHE_MS:2000,QUOTE_MAX_AGE:10000,UPSTREAM_TIMEOUT:8000,UPSTREAM_MAX_BODY_BYTES:2097152,
  Y429_BASE:30000,Y429_CAP:900000,Y_TASK_DEADLINE:20000,HOST_QUEUE_MAX:32,HOST_DEADLINE_MS:20000,
  HTTP_ACTIVE_MAX:24,HTTP_QUEUE_MAX:48,HTTP_CLIENT_QUOTA:120,HTTP_SNAPSHOT_QUOTA:600,TRUST_PROXY_LOOPBACK:'0',HTTP_REQUEST_DEADLINE_MS:20000,HTTP_SEARCH_DEADLINE_MS:12000,
  HTTP_QUOTE_ACTIVE_MAX:8,HTTP_QUOTE_QUEUE_MAX:16,HTTP_HISTORY_ACTIVE_MAX:4,HTTP_HISTORY_QUEUE_MAX:16,
  HISTORY_TOTAL_DEADLINE_MS:20000,HISTORY_EXECUTION_DEADLINE_MS:25000,HISTORY_MAX_ACTIVE:2,HISTORY_MAX_QUEUE:16,
  HISTORY_MAX_SYMBOLS:MAX_WATCHLIST_SYMBOLS,HISTORY_EXPAND_AFTER_MS:5000,HISTORY_MAX_BYTES:50331648,RECOVERY_MAX_BYTES:8388608,
  SSE_MAX_CONNECTIONS:32,SSE_MAX_BUFFER_BYTES:8388608,CACHE_BUDGET_BYTES:67108864,
  ENRICH_OPEN_MS:60000,ENRICH_CLOSED_MS:900000,ENRICH_BREAK_MS:300000,DISK_PATH:'',
  LOG_BUFFER_BYTES:262144,LOG_SAMPLE_LIMIT:20,
  FUNDAMENTALS_ENABLED:'1',FUNDAMENTALS_TTL_MS:21600000,FUNDAMENTALS_RETRY_MS:300000,FUNDAMENTALS_MAX_AGE_MS:604800000,
  SLOW_TTL:300000,NEWS_TTL:540000,NEWS_FAILURE_COOLDOWN:60000,NEWS_MAX_ENTRIES:48,NEWS_MAX_ACTIVE:12,
  AUTH_TTL:3300000,AUTH_FAILURE_COOLDOWN:60000,FX_FAILURE_COOLDOWN:60000,
  ALPACA_ENABLED:'0',ALPACA_FEED:'iex',APCA_API_KEY_ID:'',APCA_API_SECRET_KEY:'',
  ALPACA_MAX_SYMBOLS:12,ALPACA_SNAPSHOT_MS:60000,ALPACA_REST_MIN_GAP_MS:2000,ALPACA_ACTIVE_TTL_MS:300000,
  HISTORY_BACKGROUND_ENABLED:'1',HISTORY_STATE_PATH:'./state/history.json',HISTORY_REFRESH_MS:60000,
  SAMPLES_BACKGROUND_ENABLED:'1',SAMPLES_STATE_PATH:'./state/samples',SAMPLES_MAX_BYTES:100663296,
  MACRO_BACKGROUND_ENABLED:'1',MACRO_STATE_PATH:'./state/macro.json',MACRO_CONTEXT_MS:30000,MACRO_NEWS_MS:60000,
  MACRO_WEBHOOK_URL:'',MACRO_WEBHOOK_TOKEN:'',TE_API_KEY:'',FINNHUB_TOKEN:'',LOG_LEVEL:'info',LOG_FILE:'./logs/panel.log',LOG_MAX_BYTES:10485760,LOG_MAX_FILES:3
});
export function loadConfig(input={}){
  const result={...DEFAULTS};
  for(const [key,def] of Object.entries(DEFAULTS)){
    if(input[key]==null)continue;
    if(input[key]===''&&!['LLM_KEY_STORE_PATH','SAMPLES_STATE_PATH','MACRO_STATE_PATH','HISTORY_STATE_PATH','RECOVERY_PATH','LOG_FILE'].includes(key))continue;
    const value=typeof def==='number'?Number(input[key]):String(input[key]);
    if(typeof def==='number'&&(!Number.isInteger(value)||value<0||!Number.isSafeInteger(value)))throw new TypeError('配置必须为非负整数：'+key);
    result[key]=value;
  }
  if(result.LLM_API_KEY&&!/^[A-Za-z0-9_-]{32,256}$/.test(result.LLM_API_KEY))throw new TypeError('LLM_API_KEY must be 32-256 URL-safe characters');
  if(result.LLM_API_KEY&&result.LLM_API_KEY===result.STATS_TOKEN)throw new TypeError('Read-only and administrator keys must differ');
  for(const k of ['API_V1_DEPRECATION_AT','API_V1_SUNSET_AT'])if(result[k]&&(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$/.test(result[k])||!Number.isFinite(Date.parse(result[k]))||new Date(result[k]).toISOString().replace('.000Z','Z')!==result[k]))throw new TypeError(k+' 必须为有效UTC日期时间');
  if(result.API_V1_SUNSET_AT&&(!result.API_V1_DEPRECATION_AT||Date.parse(result.API_V1_SUNSET_AT)<Date.parse(result.API_V1_DEPRECATION_AT)))throw new TypeError('Sunset 不得早于 Deprecation');
  if(result.POLL_MS<1000||result.POLL_MS>60000)throw new TypeError('POLL_MS 必须为 1000～60000');
  if(!['sina','tencent'].includes(result.POLL_PRIMARY))throw new TypeError('POLL_PRIMARY 必须为 sina 或 tencent');
  if(result.PORT>65535)throw new TypeError('PORT 超出范围');
  if(!['reference','market'].includes(result.FX_MODE))throw new TypeError('FX_MODE 必须为 reference 或 market');
  for(const key of ['FUNDAMENTALS_ENABLED','TRUST_PROXY_LOOPBACK','REALTIME_SNAPSHOTS','PUBLIC_SOURCE_REDUNDANCY','ALPACA_ENABLED','MACRO_BACKGROUND_ENABLED','HISTORY_BACKGROUND_ENABLED','SAMPLES_BACKGROUND_ENABLED'])if(!['0','1'].includes(result[key]))throw new TypeError(key+' 必须为 0 或 1');
  if(result.HISTORY_REFRESH_MS<60000||result.HISTORY_REFRESH_MS>3600000)throw new TypeError('HISTORY_REFRESH_MS 必须为 60000～3600000');
  if(result.MACRO_CONTEXT_MS<30000||result.MACRO_CONTEXT_MS>600000)throw new TypeError('MACRO_CONTEXT_MS 必须为 30000～600000');
  if(result.MACRO_NEWS_MS<60000||result.MACRO_NEWS_MS>900000)throw new TypeError('MACRO_NEWS_MS 必须为 60000～900000');
  if(result.MACRO_WEBHOOK_URL&&!result.MACRO_WEBHOOK_URL.startsWith('https://'))throw new TypeError('MACRO_WEBHOOK_URL 必须为 https 地址');
  if(result.FUNDAMENTALS_TTL_MS<60000||result.FUNDAMENTALS_TTL_MS>86400000||result.FUNDAMENTALS_RETRY_MS<60000||result.FUNDAMENTALS_RETRY_MS>900000||result.FUNDAMENTALS_MAX_AGE_MS<result.FUNDAMENTALS_TTL_MS||result.FUNDAMENTALS_MAX_AGE_MS>2592000000)throw new TypeError('基础资料缓存间隔或最大保留期无效');
  if(result.Y429_CAP<result.Y429_BASE)throw new TypeError('退避上限小于初始等待');
  if(!['debug','info','warn','error'].includes(result.LOG_LEVEL))throw new TypeError('LOG_LEVEL 无效');
  const ranges={HOST_QUEUE_MAX:[0,256],HOST_DEADLINE_MS:[1,300000],HTTP_ACTIVE_MAX:[1,256],HTTP_CLIENT_QUOTA:[1,10000],HTTP_SNAPSHOT_QUOTA:[1,10000],HTTP_QUEUE_MAX:[0,512],
    HTTP_QUOTE_ACTIVE_MAX:[1,256],HTTP_QUOTE_QUEUE_MAX:[0,512],HTTP_HISTORY_ACTIVE_MAX:[1,256],HTTP_HISTORY_QUEUE_MAX:[0,512],
    HTTP_REQUEST_DEADLINE_MS:[1,300000],HTTP_SEARCH_DEADLINE_MS:[1,300000],HISTORY_TOTAL_DEADLINE_MS:[1,300000],HISTORY_EXECUTION_DEADLINE_MS:[1,300000],
    HISTORY_MAX_ACTIVE:[1,16],HISTORY_MAX_QUEUE:[0,256],HISTORY_MAX_SYMBOLS:[12,MAX_WATCHLIST_SYMBOLS],HISTORY_EXPAND_AFTER_MS:[0,3600000],
    SSE_MAX_CONNECTIONS:[1,256],SSE_MAX_BUFFER_BYTES:[4096,67108864],HISTORY_MAX_BYTES:[1048576,536870912],RECOVERY_MAX_BYTES:[65536,67108864],CACHE_BUDGET_BYTES:[1048576,1073741824],
    ENRICH_OPEN_MS:[10000,300000],ENRICH_CLOSED_MS:[10000,3600000],ENRICH_BREAK_MS:[10000,900000],LOG_BUFFER_BYTES:[1024,8388608],LOG_SAMPLE_LIMIT:[1,1000]};
  for(const [key,[min,max]] of Object.entries(ranges))if(result[key]<min||result[key]>max)throw new TypeError(`${key} 必须为 ${min}～${max}`);
  if(result.SAMPLES_MAX_BYTES<65536||result.SAMPLES_MAX_BYTES>134217728)throw new TypeError('SAMPLES_MAX_BYTES 必须为 65536～134217728');
  if(result.ENRICH_CLOSED_MS<result.ENRICH_OPEN_MS||result.ENRICH_BREAK_MS<result.ENRICH_OPEN_MS)throw new TypeError('休市/午休补充间隔不得短于开市间隔');
  if(result.HISTORY_MAX_BYTES+result.RECOVERY_MAX_BYTES+result.SSE_MAX_BUFFER_BYTES>result.CACHE_BUDGET_BYTES)throw new TypeError('历史、恢复及 SSE 缓冲预算之和超过 CACHE_BUDGET_BYTES');
  return Object.freeze(result);
}
