import assert from 'node:assert/strict';
const {intradayLiveFields,intradayObservationStatus}=await import('../lib/intraday-freshness.js').catch(()=>({}));
assert.equal(typeof intradayLiveFields,'function','explicit latest-quote point helper is required');
const now=Date.parse('2026-09-08T14:41:44Z'),t=now/1000;
const history=Object.freeze([Object.freeze({t:t-25,c:717.81,v:100})]);
const q={symbol:'QQQ',currency:'USD',price:718.01,quoteAt:now,fetchedAt:now,src:'naver-us',marketState:'REGULAR',charts:{intraday:history}};
const options={now,historyCurrency:'USD'};
const live=intradayLiveFields(q,options);
assert.deepEqual(live,{intradayLiveStatus:'ready',intradayLivePoint:{t,c:718.01,v:null,source:'naver-us',currency:'USD',sessionDate:'2026-09-08',historyDate:'2026-09-08'}});
assert.equal(q.charts.intraday,history);assert.equal(history.length,1);assert.equal(history[0].c,717.81);
for(const patch of [{stale:true},{pending:true},{recovery:true},{error:'offline'},{staleInfo:{reason:'offline'}},{price:0},{price:NaN},{quoteAt:now+1},{quoteAt:now-26000}])assert.equal(intradayLiveFields({...q,...patch},options).intradayLivePoint,null);
for(const state of ['CLOSED','HOLIDAY','BREAK','UNKNOWN'])assert.equal(intradayLiveFields({...q,marketState:state},options).intradayLivePoint,null);
assert.equal(intradayLiveFields({...q,quoteAt:now-3600000,charts:{intraday:[{t:t-3601,c:700}]}},options).intradayLivePoint,null,'hour-old quote is not current merely because its date matches');
const closeAt=Date.parse('2026-09-08T20:00:01Z');
assert.equal(intradayLiveFields({...q,quoteAt:closeAt-2000,charts:{intraday:[{t:closeAt/1000-3,c:718}]}},{now:closeAt,historyCurrency:'USD'}).intradayLivePoint,null,'cached REGULAR label cannot survive actual session transition');
for(const old of [[],[{t:t-86400,c:717,v:1}]])assert.equal(intradayLiveFields({...q,charts:{intraday:old}},options).intradayLiveStatus,'waiting-history');
const subunit={...q,symbol:'VOD.L',currency:'GBp'};
assert.equal(intradayLiveFields(subunit,{now,historyCurrency:'GBP'}).intradayLiveStatus,'unavailable');
assert.equal(intradayLiveFields(subunit,{now,historyCurrency:'GBp'}).intradayLiveStatus,'ready');
const cnUpdate={symbol:'300750.SZ',marketState:'CLOSED',quoteAt:1788855279000,charts:{intraday:[{t:1788850500,c:335.43}]}};
const cnStatus=intradayObservationStatus(cnUpdate,{now,feedDelayMinutes:0});
assert.equal(cnStatus.dataComparable,false);assert.equal(cnStatus.dataStale,false);assert.equal(cnStatus.dataAsOf,1788850500000);
console.log('PASS independent live point, raw unit, no fabricated volume/history, day and timestamp guards');
