import assert from 'node:assert/strict';
import {createReferenceFx,parseEcbRates,parseFrankfurterRates} from '../lib/providers/reference-fx.js';
import {createFxService} from '../lib/fx-service.js';
const now=Date.parse('2026-09-05T12:00:00Z');
const xml=`<gesmes:Envelope><Cube><Cube time='2026-09-04'><Cube currency='USD' rate='1.2'/><Cube currency='CNY' rate='8.4'/><Cube currency='JPY' rate='180'/><Cube currency='KRW' rate='1680'/><Cube currency='HKD' rate='9.36'/></Cube></Cube></gesmes:Envelope>`;
const rates={USD:7,JPY:150,KRW:1400,HKD:7.8};
const approx=(actual,expected)=>{for(const k of Object.keys(expected))assert.ok(Math.abs(actual[k]-expected[k])<1e-9,k);};
approx(parseEcbRates(xml,now).rates,rates);
assert.throws(()=>parseEcbRates('<!DOCTYPE x>'+xml,now));
assert.throws(()=>parseEcbRates(xml.replace("rate='8.4'","rate='NaN'"),now));
assert.throws(()=>parseEcbRates(xml.replace('2026-09-04','2026-01-04'),now));
assert.throws(()=>parseEcbRates(xml.replace('</Cube></Cube></gesmes:Envelope>',''),now));
assert.throws(()=>parseEcbRates(xml.replace("<Cube currency='USD' rate='1.2'/>",'')+"<Cube currency='USD' rate='1.2'/>",now));
const rows=Object.entries({CNY:7,JPY:150,KRW:1400,HKD:7.8}).map(([quote,rate])=>({base:'USD',quote,rate,date:'2026-09-04',providers:[{key:'ECB',date:'2026-09-04',rate}]}));
approx(parseFrankfurterRates(JSON.stringify(rows),now).rates,rates);
assert.throws(()=>parseFrankfurterRates(JSON.stringify(rows.map((r,i)=>i? r:{...r,date:'2026-09-03'})),now));
let calls=[];
const ref=createReferenceFx({now:()=>now,httpsGet:async url=>{calls.push(url);return url.includes('ecb.europa')?{status:503,body:'unavailable'}:{status:200,body:JSON.stringify(rows)};}});
const [a,b]=await Promise.all([ref.getRates(),ref.getRates()]);
assert.equal(a.transport,'frankfurter-ecb');assert.deepEqual(a,b);assert.equal(calls.length,2);
await ref.getRates();assert.equal(calls.length,2);
let time=now,primary=false;
const fx=createFxService({now:()=>time,getPrimary:async()=>primary?rates:{},primaryMetadata:()=>({fxStale:false,fxAsOf:time}),getReference:()=>ref.getRates()});
approx(await fx.getFxRates(),rates);assert.equal(fx.fxMetadata().fxKind,'reference');assert.equal(fx.fxMetadata().fxDate,'2026-09-04');
time+=61000;primary=true;await fx.getFxRates();assert.equal(fx.fxMetadata().fxKind,'market');
const fail=createFxService({now:()=>time,getPrimary:async()=>{throw new Error('offline');},getReference:async()=>{throw new Error('offline');}});
assert.deepEqual(await fail.getFxRates(),{});assert.equal(fail.fxMetadata().fxStale,true);
let release,attempts=0;
const concurrent=createFxService({now:()=>time,getPrimary:()=>{attempts++;return new Promise(r=>{release=r;});},getReference:async()=>{throw new Error('unused');}});
const p1=concurrent.getFxRates(),p2=concurrent.getFxRates();release(rates);
assert.deepEqual(await p1,await p2);assert.equal(attempts,1);
time+=121000;assert.equal(concurrent.fxMetadata().fxStale,true);
console.log('PASS coherent reference FX, strict dates/values, mirror fallback, single-flight and primary recovery');
