import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import * as tar from 'tar';
import { sourceFiles } from '../scripts/files.mjs';
import { snapshotSources, beginVerification, recordStage, requireCompleteVerification, REQUIRED_STAGES } from '../scripts/gate-state.mjs';
import { createRelease, releaseFiles, verifyArchive } from '../scripts/release.mjs';
import { coverageFailures, CRITICAL_FILES } from '../scripts/coverage.mjs';
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'qqqsp-v62-tooling-'));
const put = (file, text) => { fs.mkdirSync(path.dirname(path.join(root, file)), { recursive: true }); fs.writeFileSync(path.join(root, file), text); };
try {
  put('VERSION', '62'); put('server.js', 'export const app = true;'); put('package.json', '{"type":"module"}'); put('package-lock.json', '{}');
  put('mkt.mjs', 'export const calendarCoverageStatus = now => ({ok:now < Date.UTC(2090,0,1)});');
  put('data/market-calendars.json', '{}');
  put('public/app.js', "navigator.serviceWorker.register('/sw.js?v=62');");
  put('public/sw.js', "const VERSION = 'v62';\nconst CORE = ['/','/app.js?v=62'];");
  put('public/index.html', '<script src="/app.js?v=62"></script><a href="/app.js?v=62"></a><a href="/app.js?v=62"></a><a href="/app.js?v=62"></a>');
  put('release-manifest.json', '{"old":true}');
  assert(!sourceFiles(root).includes('release-manifest.json'));
  assert(!releaseFiles(root).includes('release-manifest.json'));
  const snapshot = snapshotSources(root); put('release-manifest.json', '{"old":"changed"}'); assert.deepEqual(snapshotSources(root), snapshot);
  beginVerification(root, { synthetic: true });
  assert.throws(() => requireCompleteVerification(root), /Synthetic/);
  assert.throws(() => requireCompleteVerification(root, { allowSynthetic: true }), /syntax/);
  for (const stage of REQUIRED_STAGES) recordStage(root, stage, stage === 'coverage' ? { testsPassed: true, failed: [] } : {}, { synthetic: true });
  requireCompleteVerification(root, { allowSynthetic: true });
  fs.mkdirSync(path.join(root, 'coverage')); fs.rmSync(path.join(root, 'coverage'), { recursive: true });
  requireCompleteVerification(root, { allowSynthetic: true });
  const a = await createRelease(root, path.join(root, 'dist/a'), { allowSynthetic: true });
  const b = await createRelease(root, path.join(root, 'dist/b'), { allowSynthetic: true });
  assert.equal(a.digest, b.digest); await verifyArchive(a.output);
  await assert.rejects(() => createRelease(root, path.join(root, 'dist/prod')), /Synthetic/);
  const evidenceFile = path.join(root, '.verification/stages.json'), evidence = JSON.parse(fs.readFileSync(evidenceFile));
  delete evidence.stages.syntax; fs.writeFileSync(evidenceFile, JSON.stringify(evidence));
  await assert.rejects(() => createRelease(root, path.join(root, 'dist/fail'), { allowSynthetic: true }), /syntax/);
  recordStage(root, 'syntax', {}, { synthetic: true });
  // Source-matched but calendar no longer covers the required current horizon.
  const future = Date.UTC(2091, 0, 1);
  const fresh = JSON.parse(fs.readFileSync(evidenceFile)); fresh.startedAt = future; for (const value of Object.values(fresh.stages)) value.at = future;
  fs.writeFileSync(evidenceFile, JSON.stringify(fresh));
  await assert.rejects(() => createRelease(root, path.join(root, 'dist/expired-calendar'), { allowSynthetic: true, now: future }), /Calendar coverage/);
  const unpack = path.join(root, 'dist/unpack'); fs.mkdirSync(unpack); await tar.extract({ file: a.output, cwd: unpack });
  const folder = path.join(unpack, 'qqqsp-v62');
  const manifest = JSON.parse(fs.readFileSync(path.join(folder, 'release-manifest.json')));
  fs.writeFileSync(path.join(folder, 'server.js'), 'tampered');
  const bad = path.join(root, 'dist/bad.tar.gz');
  await tar.create({ file: bad, cwd: unpack }, [...manifest.files.map(e => 'qqqsp-v62/' + e.path), 'qqqsp-v62/release-manifest.json']);
  await assert.rejects(() => verifyArchive(bad), /bytes differ/);
  const duplicate = path.join(root, 'dist/duplicate.tar.gz');
  await tar.create({ file: duplicate, cwd: unpack }, ['qqqsp-v62/server.js', 'qqqsp-v62/server.js']);
  await assert.rejects(() => verifyArchive(duplicate), /Duplicate/);
  const score = pct => Object.fromEntries(['lines','functions','branches'].map(k => [k, {pct}]));
  const critical = Object.fromEntries(CRITICAL_FILES.map(file => [file, score(100)]));
  assert.deepEqual(coverageFailures(score(90), {backend:score(90), browser:score(90)}, critical), []);
  assert(coverageFailures(score(90), {backend:score(90), browser:score(79)}, critical).includes('browser.lines'));
  delete critical[CRITICAL_FILES[0]];
  assert(coverageFailures(score(90), {backend:score(90), browser:score(90)}, critical).includes(CRITICAL_FILES[0]+'.branches'));
  console.log('PASS v62 release evidence, exact archive verification and independent coverage floors');
} finally { fs.rmSync(root, { recursive: true, force: true }); }
