import assert from 'node:assert/strict';
import {createHistoryService} from '../lib/history-service.js';
const time=Date.parse('2026-09-10T03:00:00Z');
const sample=(symbol='QQQ')=>({meta:{symbol,dataGranularity:'1d',currency:'USD',exchangeTimezoneName:'America/New_York',instrumentType:'ETF',firstTradeDate:Date.parse('2024-12-30T15:00:00Z')/1000},timestamp:['2024-12-30','2024-12-31','2025-01-02'].map(x=>Date.parse(x+'T15:00:00Z')/1000),indicators:{quote:[{open:[10,11,12],high:[13,14,15],low:[8,9,10],close:[12,13,14],volume:[100,200,300]}]}});
let at=time,calls=0;
const service=createHistoryService({fetchChart:async symbol=>{calls++;return sample(symbol);},now:()=>at});
const [w,m,y]=await Promise.all(['weekly','monthly','yearly'].map(p=>service.get('QQQ',p,{count:500})));
assert.equal(calls,1);assert.equal(w.seriesId,y.seriesId);assert.equal(m.seriesId,y.seriesId);
assert.equal(y.returnedCount,2);assert.equal(y.hasMore,false);assert.equal(y.sourceCheckedAt,time);
const page=await service.get('QQQ','yearly',{count:1,before:'2025-01-01',seriesId:y.seriesId});
assert.equal(page.bars[0].periodStart,'2024-01-01');assert.equal(page.returnedCount,1);
await assert.rejects(service.get('QQQ','yearly',{seriesId:'different'}),e=>e.statusCode===409);
await assert.rejects(service.get('QQQ','yearly',{before:'2026-02-30'}));
const daily=await service.get('QQQ','daily',{count:79});assert.equal(daily.returnedCount,3);
assert.equal(daily.bars.at(-1).c,14);
service.close();await assert.rejects(service.get('QQQ','yearly'),e=>e.code==='STOPPED');service.reopen();await service.get('QQQ','yearly');service.close();
const wrong=createHistoryService({fetchChart:async()=>({...sample(),meta:{...sample().meta,dataGranularity:'1mo'}}),now:()=>time});
await assert.rejects(wrong.get('QQQ','yearly'),e=>e.code==='HISTORY_GRANULARITY');wrong.close();
const bounded=createHistoryService({fetchChart:async symbol=>sample(symbol),now:()=>time,maxEntries:2});
for(const symbol of ['QQQ','SPY','AAPL'])await bounded.get(symbol,'yearly');assert.equal(bounded.diagnostics().entries,2);bounded.close();
let resolveSlow;
const slow=createHistoryService({fetchChart:()=>new Promise(resolve=>{resolveSlow=resolve;}),now:()=>time,deadlineMs:50});
await assert.rejects(slow.get('QQQ','yearly'),e=>e.code==='HISTORY_TIMEOUT');
slow.close();resolveSlow(sample());await new Promise(resolve=>setTimeout(resolve,0));assert.equal(slow.cache.size,0);
let failure=false;
const stale=createHistoryService({fetchChart:async()=>{if(failure)throw Object.assign(new Error('limited'),{code:'RATE_LIMITED',retryAt:at+60000});return sample();},now:()=>at,cacheTtl:100});
const good=await stale.get('QQQ','yearly');at+=200;failure=true;
const degraded=await stale.get('QQQ','yearly');assert.equal(degraded.stale,true);assert.equal(degraded.sourceCheckedAt,good.sourceCheckedAt);assert.equal(degraded.status,'stale');stale.close();
console.log('History service sharing, metadata, pagination, generation, budgets, timeout and stale fallback passed');
