import assert from 'node:assert/strict';
process.env.PANEL_TEST_AUTOSTART='0';
const {createApplication}=await import('../server.js');
const now=Date.parse('2026-09-06T00:00:00Z'),calls=[];
const xml=`<Envelope><Cube><Cube time='2026-09-04'><Cube currency='USD' rate='1.2'/><Cube currency='CNY' rate='8.4'/><Cube currency='JPY' rate='180'/><Cube currency='KRW' rate='1680'/><Cube currency='HKD' rate='9.36'/></Cube></Cube></Envelope>`;
const transport={httpsGet:async(url)=>{calls.push(url);if(url.includes('eurofxref-daily.xml'))return {status:200,body:xml};throw new Error('simulated primary outage');},close(){}};
const quote={symbol:'QQQ',currency:'USD',price:500,quoteAt:now-86400000,ts:now-86400000,fetchedAt:now,marketState:'CLOSED',src:'tx-us'};
const app=createApplication({env:{PUBLIC_SOURCE_REDUNDANCY:'1'},now:()=>now,transport,providerOverrides:{fetchQuote:async()=>quote}});
assert.equal(calls.length,0,'construction must not contact upstream');
app.services.breaker.hit('fixture');
await app.services.fx.getFxRates();
assert.equal(calls.length,1,'blocked primary FX must not be queried');
app.services.breaker.expire();
const q=await app.getCachedQuote('QQQ');
assert.equal(q.fxKind,'reference');assert.equal(q.fxSource,'ECB');assert.equal(q.fxStale,false);assert.equal(q.currency2cny,7.000000000000001);
assert.equal(calls.length,1,'blocked primary FX must not be queried');
assert.equal(app.cacheSizes().redundancy.recovery.enabled,false);assert.ok(app.services.officialNews);
await app.stop();
const disabled=createApplication({env:{},transport});assert.equal(disabled.services.redundancy,null);await disabled.stop();
console.log('PASS composition flag, independent FX during primary outage, provider wiring and diagnostics');
