import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import { loadApp } from './_harness.mjs';
const sandbox = { window: {}, AbortController, setTimeout, clearTimeout, fetch: () => {} };
for (const name of ['panel-scheduler.js', 'panel-network.js']) vm.runInNewContext(fs.readFileSync(new URL('../public/modules/' + name, import.meta.url), 'utf8'), sandbox);
const createNetwork = sandbox.window.PANEL_NETWORK.createNetwork;
let signal;
const stalled = createNetwork({ timeoutMs: 25, fetchImpl: async (_, options) => {
  signal = options.signal;
  return { ok: true, status: 200, json: () => new Promise(() => {}) };
} });
await assert.rejects(stalled.request('news', '/api/news'), /超时|timeout/i, 'body parsing must be inside the total deadline');
assert.equal(signal.aborted, true);
assert.equal(stalled.inFlight.size, 0);
console.log('PASS full response body deadline and cleanup');
let releaseOld;
const replacement = createNetwork({ timeoutMs: 1000, fetchImpl: async url => ({ ok: true, status: 200, json: () => url === '/old' ? new Promise(resolve => { releaseOld = resolve; }) : Promise.resolve(['new']) }) });
const old = replacement.request('search', '/old');
const rejected = assert.rejects(old, /取消|abort/i);
await new Promise(resolve => setImmediate(resolve));
const fresh = await replacement.request('search', '/new', { replace: true });
await rejected;
releaseOld(['old']);
assert.deepEqual(await fresh.json(), ['new']);
assert.equal(replacement.inFlight.size, 0);
console.log('PASS replacement cancels full old response');
const env = await loadApp({ watchlist: ['QQQ'] }); await env.drain();
env.fetch.push('market', { body: [{ symbol: 'QQQ', price: 100, change: 1, changePct: 1, currency: 'USD', instrumentType: 'ETF', marketState: 'CLOSED', ts: Date.now(), charts: { intraday: [], daily30: [] } }] });
await env.hooks().refresh(false);
const card = env.hooks().cardCache.get('QQQ');
for (const fn of card.closeBtn._handlers.click || []) fn({});
assert.equal(env.hooks().lastDataRef().length, 0);
assert.doesNotMatch(env.byId('digest').innerHTML, /自选 1/);
assert.equal(env.byId('updateAt').textContent, '自选为空');
console.log('PASS removal updates all derived state immediately');

const labeled = await loadApp({ watchlist: ['QQQ'] }); await labeled.drain();
const failedCard = labeled.hooks().cardCache.get('QQQ');
assert.equal(failedCard.retryBtn.hidden, false, 'missing quote must offer retry');
labeled.hooks().renderNews(failedCard, [{title:'市场标题',t:Date.now(),src:'Fixture',link:'https://example.com/news',sent:'利好',general:true}], {stale:true,error:'暂不可用'});
assert.match(failedCard.newslist.children.map(node=>node.innerHTML).join(''), /市场资讯/);
assert.match(failedCard.newslist.children.map(node=>node.innerHTML).join(''), /规则·利好/);
assert.match(failedCard.newshead.textContent, /缓存/);
const encoded = Buffer.from(JSON.stringify({QQQ:{stale:true,error:'暂不可用'}})).toString('base64url');
const metadata = labeled.sandbox.window.PANEL_CLIENT.decodeNewsMetadata({get: key => key === 'X-News-Meta-Encoding' ? 'base64url-json' : encoded});
assert.equal(metadata.QQQ.error, '暂不可用');
assert.equal(JSON.stringify(labeled.sandbox.window.PANEL_STATE.createState({getItem(){throw new Error('blocked');}}).loadWatchlist('watch',['QQQ'])), '["QQQ"]');
console.log('PASS retry, general/rule labels, Unicode metadata and blocked storage');
