import assert from 'node:assert/strict';
import { loadApp } from './_harness.mjs';
const failures=[];
async function test(name, run) { try { await run(); console.log('PASS '+name); } catch(e) { failures.push(name); console.log('FAIL '+name+': '+e.message); } }
const bars=n=>Array.from({length:n},(_,i)=>({t:1700000000+i*60,o:100+i,h:102+i,l:99+i,c:101+i,v:i+1}));
const quote=(extra={})=>({symbol:'QQQ',price:200,currency:'USD',instrumentType:'ETF',market:'美股',marketState:'CLOSED',priceSession:'POST',regularPrice:199,change:1,changePct:1,charts:{intraday:bars(100),daily30:bars(150)},...extra});
async function ready(options={}) {const e=await loadApp({watchlist:['QQQ'],...options});await e.drain();return e;}
async function show(e,q=quote()) {e.fetch.push('market',{body:[q]});await e.hooks().refresh(false);return e.hooks().cardCache.get('QQQ');}
const fire=(el,type,extra={})=>(el._handlers[type]||[]).forEach(fn=>fn({target:el,preventDefault(){},...extra}));
await test('09 fractional DPR unchanged draw never resets backing canvas',async()=>{const e=await ready({dpr:1.25});const q=e.hooks().cardCache.get('QQQ');q.cv.getBoundingClientRect=()=>({width:281,left:0,height:240});await show(e);const writes=q.cv._sizeWrites;e.hooks().render(q);assert.equal(q.cv._sizeWrites,writes);assert.equal(q.cv.width,351);});
await test('10 follow latest advances while historical view and timeframe states remain independent',async()=>{const e=await ready();const q=await show(e);const start=q.winStart;await show(e,quote({charts:{intraday:bars(102),daily30:bars(150)}}));assert.equal(q.winStart,start+2);q.slider.value='5';fire(q.slider,'input');fire(q.tabs[1],'click');assert.equal(q.winStart,90);fire(q.tabs[0],'click');assert.equal(q.winStart,5);await show(e,quote({charts:{intraday:bars(104),daily30:bars(150)}}));assert.equal(q.winStart,5);});
await test('11 changed watchlist issues news request for new symbol and discards old generation',async()=>{const e=await ready();const deferred=e.fetch.push('news',{body:{QQQ:[]},defer:true});const old=e.hooks().refreshNews();e.fetch.push('news',{body:{QQQ:[],AAPL:[{title:'Apple current',t:10,src:'Fixture',link:'https://example.com/a'}]}});e.hooks().addToWatch('AAPL','Apple');deferred.resolve();await old;await e.drain();assert.ok(e.fetchLog.some(u=>u.includes('/api/news')&&u.includes('AAPL')));assert.match(e.hooks().cardCache.get('AAPL').newslist.children.map(node=>node.innerHTML).join(''),/Apple current/);});
await test('12 macro failure exits loading and cached errors remain truthful with retry',async()=>{const e=await ready();e.fetch.push('macro',{status:500,body:{}});await e.hooks().refreshMacro();assert.match(e.byId('macroStatus').textContent,/失败|不可用/);assert.equal(e.byId('macroRetry').hidden,false);e.fetch.push('macro',{body:{items:[{title:'cached',topic:'经济',t:10}],updatedAt:1000,stale:true,error:'upstream unavailable'}});assert.equal(await e.hooks().refreshMacro(),false);assert.match(e.byId('macroStatus').textContent,/缓存|过期/);});
await test('13 macro filters keep focused node across changing results',async()=>{const e=await ready();e.fetch.push('macro',{body:{items:[{title:'one',topic:'经济',t:10}]}});await e.hooks().refreshMacro();const filters=e.byId('mfilters'),writes=filters._htmlWrites;const target=filters.children.find(x=>x.dataset.f==='经济');assert.ok(target);target.focus();e.fetch.push('macro',{body:{items:[{title:'two',topic:'经济',t:11}]}});await e.hooks().refreshMacro();assert.equal(filters.children.find(x=>x.dataset.f==='经济'),target);assert.equal(filters._htmlWrites,writes);});
await test('14 keyboard history exposes textual OHLC and selected point',async()=>{const e=await ready();const q=await show(e);fire(q.cv,'keydown',{key:'Home'});assert.equal(q.hoverIdx,0);const detail=q.el.querySelector('.chart-point').textContent;assert.match(detail,/QQQ/);assert.match(detail,/开.*高.*低.*收.*量/);fire(q.cv,'keydown',{key:'ArrowRight'});assert.equal(q.hoverIdx,1);});
await test('15 quote session survives weekend close and ETF is explicit',async()=>{const e=await ready();const q=await show(e);assert.equal(q.phasetag.hidden,false);assert.match(q.phasetag.textContent,/盘后/);assert.match(q.extRow.textContent+q.extRow.innerHTML,/常规.*199/);assert.match(q.friendly.textContent,/ETF/);});
await test('18 Retry-After defers network traffic even for manual repeated refresh',async()=>{const e=await ready();e.fetch.push('market',{status:429,body:[],headers:{'Retry-After':'60'}});await e.hooks().refresh(false);const before=e.countFetch('/api/market');await e.hooks().refresh(false);await e.hooks().refresh(true);assert.equal(e.countFetch('/api/market'),before);assert.match(e.byId('updateAt').textContent,/重试|限流/);});
await test('30 unchanged chart poll skips layout and pointer overlay skips base drawing',async()=>{const e=await ready();const q=await show(e);let layouts=0;const original=q.cv.getBoundingClientRect;q.cv.getBoundingClientRect=()=>{layouts++;return original();};e.hooks().render(q);assert.equal(layouts,0);let clears=0;q.cv.getContext().clearRect=()=>clears++;fire(q.cv,'keydown',{key:'Home'});assert.equal(clears,0);});
if(failures.length)process.exitCode=1;
