import assert from 'node:assert/strict';
import {createHostGate} from '../lib/host-gate.js';
const __upstream={impl:null},gate=createHostGate({minGap:()=>0});
import {createBatchProvider} from '../lib/providers/batch-snapshot.js';
const {fetchSnapshotBatch,parseNaverQuote,parseTencentBatch}=createBatchProvider({httpsGet:(url,h,o)=>gate.run(url,()=>__upstream.impl(url,h,o),o)});
const row=(symbol='AAPL')=>({symbolCode:symbol,reutersCode:symbol+'.O',stockName:symbol,stockExchangeType:{code:'NSQ',nameEng:'NASDAQ',nationType:'USA',delayTime:0},closePrice:'100',compareToPreviousClosePrice:'-2',compareToPreviousPrice:{name:'FALLING'},openPrice:'102',highPrice:'103',lowPrice:'99',localTradedAt:'2026-09-04T16:00:00-04:00',marketStatus:'CLOSE',currencyType:{code:'USD'},overMarketPriceInfo:{overPrice:'101',localTradedAt:'2026-09-04T20:00:00-04:00',tradingSessionType:'AFTER_MARKET'}});
const q=parseNaverQuote(row(),'AAPL',70000);
assert.equal(q.price,101);assert.equal(q.prevClose,102);assert.equal(q.change,-1);assert.equal(q.quoteAt,Date.parse('2026-09-04T20:00:00-04:00'));assert.equal(q.priceSession,'POST');assert.equal(q.ohlcConsistent,false);assert.equal(q.feedDelayMinutes,0);assert.equal(q.pollAfterMs,70000);
assert.equal(parseNaverQuote(row(),'MSFT',70000),null);
const kr={...row(),symbolCode:'005930',itemCode:'005930',stockExchangeType:{code:'KS',nationType:'KOR',nameEng:'KOSPI',delayTime:0},currencyType:{code:'KRW'},localTradedAt:'2026-09-04T15:30:00+09:00',overMarketPriceInfo:null};
assert.equal(parseNaverQuote(kr,'005930.KQ',70000),null,'same number wrong exchange rejected');
assert.equal(parseNaverQuote(kr,'005930.KS',70000).src,'naver-kr');
let calls=[];__upstream.impl=async url=>{calls.push(url);return {status:200,body:JSON.stringify({pollingInterval:70000,datas:[row('NVDA'),row('AAPL')]}),headers:{}};};
const b=await fetchSnapshotBatch(['AAPL','NVDA'],{group:'us'});assert.equal(calls.length,1);assert.equal(b.quotes.length,2);assert.equal(b.pollAfterMs,70000);assert.equal(b.quotes.find(x=>x.symbol==='NVDA').price,101);
const fields=Array(50).fill('');Object.assign(fields,{1:'SPY',2:'SPY.AM',3:'100',4:'99',5:'98',6:'10000',30:'2026-01-05 16:00:01',31:'1',32:'1',33:'101',34:'97',35:'USD'});
const tx='v_usSPY="'+fields.join('~')+'";';
assert.equal(parseTencentBatch(tx,['SPY'])[0].quoteAt,Date.parse('2026-01-05T16:00:01-05:00'),'winter exchange time is EST');
assert.equal(parseTencentBatch(tx,['AAPL']).length,0);
calls=[];__upstream.impl=async url=>{calls.push(url);return url.includes('qt.gtimg')?{status:200,body:tx,headers:{}}:{status:429,body:'limited',headers:{'retry-after':'90'}};};
const fb=await fetchSnapshotBatch(['SPY','AAPL'],{group:'us'});assert.equal(fb.quotes.length,1);assert.equal(fb.quotes[0].symbol,'SPY');assert.ok(fb.pollAfterMs>=90000);
const before=calls.length;await assert.rejects(fetchSnapshotBatch(['005930.KS'],{group:'kr'}),e=>e.status===429&&e.retryAfterMs>80000);assert.equal(calls.length,before,'shared host cooldown prevents another market bypassing429');
__upstream.impl=null;
console.log('PASS batch snapshots: identity, sessions, timezone, ordered mapping,70s hint and shared429 cooldown');
