import assert from 'node:assert/strict';
import {loadApp} from './_harness.mjs';
const e=await loadApp({watchlist:['QQQ','SPY']});await e.drain();
const old=e.fetch.push('news',{body:{QQQ:[],SPY:[]},defer:true});
const waiting=e.hooks().refreshNews();
const spy=e.hooks().cardCache.get('SPY');
spy.closeBtn.click();
e.fetch.push('news',{body:{QQQ:[],SPY:[{title:'re-added current news',t:10,src:'fixture',link:'https://example.com/spy'}]}});
const before=e.countFetch('/api/news');
e.hooks().addToWatch('SPY','SPY ETF');
old.resolve();await waiting;await e.drain();
assert.ok(e.countFetch('/api/news')>before,'same watchlist key after invalidation needs a new generation');
assert.match(e.hooks().cardCache.get('SPY').newslist.children.map(node=>node.innerHTML).join(''),/re-added current news/);
e.fetch.push('macro',{body:{items:[{title:'recent cached macro',topic:'经济',t:10}],updatedAt:1000,stale:false,refreshing:true}});
await e.hooks().refreshMacro();
assert.equal(e.byId('macroStatus').dataset.state,'refreshing','healthy background refresh is not a source failure');
e.fetch.push('macro',{body:{items:[{title:'completed macro',topic:'经济',t:20}],updatedAt:2000,stale:false}});
e.timers.runTimeouts(2000);await e.drain();
assert.equal(e.byId('macroStatus').dataset.state,'ready');
const card=e.hooks().cardCache.get('QQQ');
card._chartWidth=260;
card.d={symbol:'QQQ',price:10,currency:'USD',charts:{intraday:[{t:1,c:10},{t:2,c:11}]}};
e.hooks().render(card);
assert.equal(card.cv.width,260,'320px viewport canvas uses actual260px content width');
console.log('PASS re-added news generation and bounded healthy macro refresh follow-up');
