import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createRedundancy} from '../lib/redundancy.js';
import {createRecoveryStore} from '../lib/recovery-store.js';
import {quoteStatus} from '../lib/http-diagnostics.js';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'qqq-redundancy-'));
const time=Date.parse('2026-09-06T00:00:00Z'),quoteAt=time-86400000;
const quote={symbol:'QQQ',price:500,currency:'USD',marketState:'CLOSED',src:'tx-us',quoteAt,ts:quoteAt,fetchedAt:time,charts:{daily30:[{t:quoteAt/1000,c:500,v:100}]}};
let current=quote,fxCalls=0;
const fx={getFxRates:async()=>{fxCalls++;return {USD:7,JPY:150,KRW:1400,HKD:7.8};},fxFallbackRates:()=>({USD:7,JPY:150,KRW:1400,HKD:7.8}),fxMetadata:()=>({fxKind:'reference',fxSource:'ECB',fxDate:'2026-09-04',fxAsOf:time-2*86400000,fxStale:false})};
try{
 const filePath=path.join(dir,'quotes.json');
 const store=createRecoveryStore({filePath,now:()=>time});
 const gateway=createRedundancy({getQuote:async()=>current,fx,recovery:store,now:()=>time});
 const first=await gateway.getCachedQuote('QQQ');
 assert.equal(first.fxKind,'reference');assert.equal(first.currency2cny,7);assert.equal(first.quoteAt,quoteAt);
 assert.equal(quoteStatus(first,time).usable,true);
 await gateway.stop();assert.ok(fs.existsSync(filePath));
 const restarted=createRecoveryStore({filePath,now:()=>time});
 current={symbol:'QQQ',pending:true,error:'offline'};
 const second=createRedundancy({getQuote:async()=>current,fx,recovery:restarted,now:()=>time});
 const old=await second.getCachedQuote('QQQ');
 assert.equal(old.recovery,true);assert.equal(old.staleInfo.reason,'offline-cache');assert.equal(old.fxStale,true);assert.equal(old.quoteAt,quoteAt);assert.equal(old.fetchedAt,time);assert.equal(quoteStatus(old,time).usable,false);
 current={...quote,price:510,quoteAt:quoteAt+1000,ts:quoteAt+1000};
 assert.equal((await second.getCachedQuote('QQQ')).recovery,undefined);
 current={...quote,stale:true,quoteAt:quoteAt+2000};
 assert.equal((await second.getCachedQuote('QQQ')).recovery,undefined,'newer stale live quote must not roll back');
 current=null;assert.equal((await second.getCachedQuote('QQQ')).recovery,true);
 await second.stop();
 const rejected=createRedundancy({getQuote:async()=>{throw new Error('offline');},fx,recovery:createRecoveryStore({filePath,now:()=>time}),now:()=>time});
 assert.equal((await rejected.getCachedQuote('QQQ')).recovery,true);
 await assert.rejects(()=>rejected.getCachedQuote('SPY'),/offline/);
 await rejected.stop();assert.ok(fxCalls>0);
 let finish,slowCalls=0;
 const slow=createRedundancy({getQuote:()=>{slowCalls++;return new Promise(r=>{finish=r;});},fx,recovery:createRecoveryStore({filePath,now:()=>time}),now:()=>time,recoveryWaitMs:5});
 const start=performance.now();const batch=await Promise.all([slow.getCachedQuote('QQQ'),slow.getCachedQuote('QQQ')]);
 assert.ok(performance.now()-start<100);assert.ok(batch.every(q=>q.recovery));assert.equal(slowCalls,1);
 finish(quote);await new Promise(r=>setTimeout(r,0));await slow.stop();
 console.log('PASS independent FX, persistent restart fallback, real timestamps, live recovery and readiness fail-closed');
}finally{fs.rmSync(dir,{recursive:true,force:true});}
