import assert from 'node:assert/strict';
import { loadApp } from './_harness.mjs';
const e=await loadApp({watchlist:['QQQ'],fakeObservers:true});await e.drain();
const panel=e.sandbox.window;
const f=panel.PANEL_FORMAT.createFormatter;
const usd=f({data:{symbol:'QQQ',currency:'USD',price:100},displayCurrency:'CNY',fxMap:{USD:7}});
const jpy=f({data:{symbol:'7203.T',currency:'JPY',price:100},displayCurrency:'USD',fxMap:{USD:7,JPY:140}});
const index=f({data:{symbol:'^N225',currency:'JPY',price:100,instrumentType:'INDEX'},displayCurrency:'CNY',fxMap:{JPY:140}});
assert.equal(usd.money(100),'¥700.00');assert.equal(jpy.money(100),'0.71');assert.equal(index.money(100),'100.00');assert.equal(usd.money(100),'¥700.00');
assert.equal(f({data:{currency:'JPY',price:100,fxStale:true},displayCurrency:'CNY',fxMap:{JPY:140}}).unit,'JPY');
console.log('PASS immutable currency/index formatters interleave without context contamination');
const makeStore=panel.PANEL_MARKET_STORE.createMarketStore, one=makeStore(),two=makeStore();
const oneBars=[{t:1,c:100}],twoBars=[{t:1,c:900}];
one.prepareQuote({symbol:'QQQ',intradayVer:1,charts:{intraday:oneBars}});two.prepareQuote({symbol:'QQQ',intradayVer:1,charts:{intraday:twoBars}});
one.prepareQuote({symbol:'QQQ',charts:{intraday:'same'},intradayLast:[1,101]});
assert.equal(two.intradayCache.QQQ.bars[0].c,900);assert.equal(one.intradayCache.QQQ.bars[0].c,101);
one.remove('QQQ');assert.equal(one.chartVersions(['QQQ']),'QQQ:0:0');assert.equal(two.chartVersions(['QQQ']),'QQQ:1:0');
console.log('PASS separate market stores isolate charts and removals');
let now=1700000000000,calls=0,mode='date';
const net=panel.PANEL_NETWORK.createNetwork({now:()=>now,fetchImpl:async()=>{calls++;return {status:mode==='date'?429:mode==='service'?503:200,ok:mode==='ok',headers:{get:()=>new Date(now+30000).toUTCString()},json:async()=>({ok:true})};}});
const first=await net.request('market','/api/market');assert.equal(first.retryAt,now+30000);
for(let i=0;i<5;i++)assert.equal((await net.request('market','/api/market')).deferred,true);
assert.equal(calls,1);mode='ok';assert.equal((await net.request('macro','/api/macro')).ok,true);assert.equal(calls,2);
now+=30000;const [a,b]=await Promise.all([net.request('market','/api/market'),net.request('market','/api/market')]);assert.equal(a.ok&&b.ok,true);assert.equal(calls,3);
mode='service';await net.request('search','/api/search');assert.equal((await net.request('search','/api/search')).deferred,true);
console.log('PASS Retry-After HTTP date and 503 defer per resource, expiration makes one deduplicated request without scheduled burst');
const bars=Array.from({length:100},(_,i)=>({t:1700000000+i,c:100+i,v:i}));
const quote=extra=>({symbol:'QQQ',price:199,currency:'USD',marketState:'CLOSED',src:'fixture',quoteAt:Date.now(),charts:{intraday:bars},...extra});
e.fetch.push('market',{body:[quote({intradayVer:1})]});await e.hooks().refresh(false);
const q=e.hooks().cardCache.get('QQQ');let clears=0;q.cv.getContext().clearRect=()=>clears++;
e.intersections[0].emit([{target:q.cv,isIntersecting:false}]);
e.fetch.push('market',{body:[quote({price:250,intradayVer:2,charts:{intraday:[...bars,{t:1700000100,c:250,v:1}]}})]});await e.hooks().refresh(false);
assert.equal(q.cur.textContent,'250.00');assert.equal(clears,0);assert.equal(q._dirty,true);
e.intersections[0].emit([{target:q.cv,isIntersecting:true}]);assert.equal(clears,1);assert.equal(q._dirty,false);assert.equal(q.plot.bars.at(-1).c,250);
let layouts=0;q.cv.getBoundingClientRect=()=>{layouts++;return {left:0,width:1000,height:240};};
for(let i=0;i<50;i++)for(const listener of q.cv._handlers.mousemove||[])listener({clientX:20+i*10});
assert.ok(layouts<=1);assert.equal(clears,1,'cursor only updates overlay');
e.resizes[0].emit([{target:q.cv,contentRect:{width:500}}]);e.timers.runTimeouts(16);assert.equal(q.cv.width,500);assert.equal(clears,2);
q.closeBtn.click();assert.equal(e.intersections[0].targets.has(q.cv),false);assert.equal(e.resizes[0].targets.has(q.cv),false);
console.log('PASS offscreen prices/status stay current while chart work defers; pointer reuses layout and overlay; resize/removal release observers');
