import assert from 'node:assert/strict';
import { currencyToCny, currencyUnitInfo } from '../lib/currency.js';
import { createFxService } from '../lib/fx-service.js';
import { createYahooService } from '../lib/yahoo.js';
import { parseEcbRates, parseFrankfurterRates } from '../lib/providers/reference-fx.js';
const rates={USD:7,GBP:.8,ZAR:18,EUR:.9,CHF:.85,CAD:1.4,AUD:1.5,INR:84,SGD:1.3,TWD:32,BRL:5.5,MXN:20};
for(const [unit,price,cny] of [['GBp',1000,87.5],['GBX',1000,87.5],['GBP',10,87.5],['ZAc',1800,7],['ZAC',1800,7],['ZAR',18,7],['EUR',.9,7],['CHF',.85,7],['CAD',1.4,7],['AUD',1.5,7],['INR',84,7],['SGD',1.3,7],['TWD',32,7],['BRL',5.5,7],['MXN',20,7]])assert.ok(Math.abs(price*currencyToCny(unit,rates)-cny)<1e-10,unit);
assert.equal(currencyUnitInfo('GBp').scale,.01);assert.equal(currencyUnitInfo('GBP').scale,1);
assert.equal(currencyToCny('GBp',rates,{index:true}),null);assert.equal(currencyToCny('GBP',rates,{fxStale:true}),null);assert.equal(currencyToCny('TWD',{USD:7}),null);assert.equal(currencyToCny('CNY',{}),1);
const now=Date.parse('2026-09-05T12:00:00Z');
const xml="<gesmes:Envelope><Cube><Cube time='2026-09-04'><Cube currency='USD' rate='1.2'/><Cube currency='CNY' rate='8.4'/><Cube currency='GBP' rate='0.96'/></Cube></Cube></gesmes:Envelope>";
const parsed=parseEcbRates(xml,now);assert.ok(Math.abs(parsed.rates.USD-7)<1e-12);assert.equal(parsed.rates.GBP,.8);assert.equal(parsed.rates.EUR,1/1.2);assert.equal(parsed.rates.TWD,undefined);
const rows=[['CNY',7],['GBP',.8]].map(([quote,rate])=>({base:'USD',quote,rate,date:'2026-09-04',providers:[{key:'ECB',date:'2026-09-04',rate}]}));
assert.deepEqual(parseFrankfurterRates(JSON.stringify(rows),now).rates,{USD:7,GBP:.8});
assert.throws(()=>parseFrankfurterRates(JSON.stringify([...rows,rows[0]]),now));
const fx=createFxService({now:()=>now,getPrimary:async()=>({USD:7,GBP:.8}),getReference:async()=>{throw new Error('unused');}});assert.deepEqual(await fx.getFxRates(),{USD:7,GBP:.8});assert.equal(fx.fxMetadata().fxStale,false);
let requests=0,charts=0;const yahoo=createYahooService({now:()=>now,env:{Y_MIN_GAP:'0'},getCrumb:async()=>({cookie:'fixture',crumb:'fixture'}),clearCrumb(){},httpsGet:async()=>{requests++;return {status:200,body:'{"quoteResponse":{"result":[]}}'};},chartOverride:async()=>{charts++;return {meta:{regularMarketPrice:7}};}});
await yahoo.getFxRates();assert.equal(requests,1);assert.equal(charts,4);await yahoo.close();
let phase=0,tick=now,chartCalls=0;
const coherent=createYahooService({now:()=>tick,env:{Y_MIN_GAP:'0'},getCrumb:async()=>({cookie:'fixture'}),httpsGet:async()=>({status:phase===2?429:200,body:JSON.stringify({quoteResponse:{result:phase===0?[{symbol:'CNY=X',regularMarketPrice:7},{symbol:'USDTWD=X',regularMarketPrice:32}]:[{symbol:'CNY=X',regularMarketPrice:7}]}})}),chartOverride:async()=>{chartCalls++;throw new Error('optional currency unavailable');}});
assert.equal((await coherent.getFxRates()).TWD,32);phase=1;tick+=61000;assert.equal((await coherent.getFxRates()).TWD,undefined,'fresh set never keeps prior optional rate');assert.equal(coherent.fxMetadata().fxStale,false);
phase=2;tick+=61000;const before=chartCalls;await coherent.getFxRates();assert.equal(chartCalls,before,'429 must not fan out to charts');await coherent.close();
let referenceCalls=0;
const currencySelection=createFxService({now:()=>now,getPrimary:async()=>({USD:7,JPY:150,KRW:1400,HKD:7.8}),primaryMetadata:()=>({fxAsOf:now,fxStale:false}),getReference:async()=>{referenceCalls++;return {rates:{USD:7.1,GBP:.8,EUR:.9,ZAR:18},observationAt:now-86400000,retrievedAt:now,date:'2026-09-04',transport:'ecb-xml'};}});
const [gbp,usd]=await Promise.all([currencySelection.getFxSnapshot('GBp'),currencySelection.getFxSnapshot('USD')]);
assert.equal(gbp.rates.GBP,.8);assert.equal(gbp.fxKind,'reference');assert.equal(gbp.fxDate,'2026-09-04');assert.equal(usd.rates.USD,7);assert.equal(usd.fxKind,'market');assert.equal(usd.fxDate,null);assert.equal(referenceCalls,1);
assert.equal(currencySelection.fxSnapshotFor('ZAc').fxKind,'reference');
assert.equal((await currencySelection.getFxSnapshot('TWD')).rates.TWD,undefined);
assert.equal(currencySelection.fxSnapshotFor('USD').fxStale,false,'missing TWD cannot stale unrelated USD');
console.log('PASS global FX, case-sensitive subunits, coherent partial reference and bounded fallback');
