import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const sandbox = { window: {}, Date, performance };
vm.createContext(sandbox);
for (const file of ['panel-state.js','panel-card-view.js']) vm.runInContext(fs.readFileSync(new URL('../public/modules/'+file,import.meta.url),'utf8'),sandbox);
const {formatQuoteAge,createQuoteClock}=sandbox.window.PANEL_STATE;
const t=1788960000000;
assert.equal(formatQuoteAge(t,t+8000),'8秒');
assert.equal(formatQuoteAge(t,t+123000),'2分03秒');
assert.equal(formatQuoteAge(t,t+3723000),'1时02分03秒');
assert.equal(formatQuoteAge(t/1000,t+8000),'8秒');
assert.match(formatQuoteAge(null,t),/^未知/);
assert.match(formatQuoteAge('bad',t),/^未知/);
assert.equal(formatQuoteAge(t+2000,t),'时间异常');
assert.equal(formatQuoteAge(t+500,t),'0秒');
let monotonic=0,wall=t;
const clock=createQuoteClock({wall:()=>wall,mono:()=>monotonic});
assert.equal(clock.sync(null,0),false);
monotonic=100;assert.equal(clock.sync(t+50,0),true);
assert.equal(clock.now(),t+100);
wall+=3600000;monotonic=1100;
assert.equal(clock.now(),t+1100,'local wall-clock changes must not change anchored time');
monotonic=2200;clock.sync(t+7000,1100);
assert.equal(clock.now(),t+2200,'slower sample must not replace recent low-RTT anchor');
clock.resume();assert.equal(clock.status().synced,false);
monotonic=2300;clock.sync(t+6050,2200);
assert.equal(clock.now(),t+6100,'recovery obtains a new server anchor');

// Exercise actual card metadata renderer with stable leaf nodes and a frozen quote.
sandbox.window.PANEL_FORMAT={esc:String,fmtVol:String,pct:String,fmtTime8:String};
let chartCalls=0;
const view=sandbox.window.PANEL_CARD_VIEW.createCardView({document:{},panelsEl:{},stripEl:{},chartController:{drawChart(){chartCalls++;}},formatterFor:()=>({}),cardCurOf:()=> 'USD',nameOf:()=>'',humanizeAge:String,UP:'red',DOWN:'green'});
function leaf(){let value='',writes=0;return {dataset:{},get textContent(){return value;},set textContent(v){value=v;writes++;},get writes(){return writes;}};}
const q={d:{symbol:'QQQ',quoteAt:t,sourceCheckedAt:t,src:'naver-us',pollAfterMs:7000,ohlcSession:'REGULAR'},quoteMeta:{},quoteDetails:leaf(),quoteAge:leaf(),sourceCheckAge:leaf()};
view.updateQuoteMeta(q,t+123000);
const detailsWrites=q.quoteDetails.writes;
const data=q.d;
view.updateQuoteMeta(q,t+124000);
assert.match(q.quoteAge.textContent,/2分04秒/);
assert.match(q.sourceCheckAge.textContent,/2分04秒/);
assert.equal(q.quoteDetails.writes,detailsWrites,'unchanged details are not rewritten each second');
assert.equal(q.d,data,'age updates must not replace quote data');
assert.equal(chartCalls,0,'age updates must not redraw charts');
assert.equal(q.quoteAge.dataset.ageComputedAtMs,String(t+124000));
q.d={...q.d,sourceCheckedAt:t+124000};
view.updateQuoteMeta(q,t+125000);
assert.match(q.quoteAge.textContent,/2分05秒/,'successful checks with old quote timestamps do not reset age');
assert.match(q.sourceCheckAge.textContent,/1秒/);
q.d={...q.d,quoteAt:t+125000};view.updateQuoteMeta(q,t+126000);
assert.match(q.quoteAge.textContent,/1秒/,'same-price newer quote time is accepted');
q.d={...q.d,quoteAt:null};view.updateQuoteMeta(q,t+126000);
assert.match(q.quoteAge.textContent,/未知/);
console.log('phase2 age: formatting, clock, recovery and leaf-render assertions passed');
