import assert from 'node:assert/strict';
import {loadApp} from './_harness.mjs';
const env=await loadApp({watchlist:['QQQ']});await env.drain();
const H=env.hooks(),state=env.win.PANEL_STATE,now=Date.now();
const sample={symbol:'QQQ',currency:'USD',price:717.54,prevClose:717.67,regularPrice:718.96,change:-.13,changePct:-.02,priceSession:'POST',marketState:'POST',quoteAt:now-16000,sourceCheckedAt:now,fetchedAt:now,charts:{intraday:[]},ext:{post:{price:717.54,change:-1.42,changePct:-.2}}};
env.fetch.push('market',{body:[sample]});await H.refresh(false);const q=H.cardCache.get('QQQ');
H.updateQuoteMeta(q,now);assert.equal(q.staleWarn.hidden,!H.quoteIsStale(sample,now),'card/header share active-age decision');
for(const d of [{...sample,marketState:'CLOSED',quoteAt:now-86400000},{...sample,marketState:'BREAK',quoteAt:now-3600000,sessionStartedAt:now-3600000},{...sample,pollAfterMs:70000,feedDelayMinutes:15,quoteAt:now-930000}])assert.equal(state.selectFreshness(d,now).stale,false,'closed/break/provider delay do not falsely age');
assert.equal(state.selectFreshness({...sample,pollAfterMs:70000,feedDelayMinutes:15,quoteAt:now-930001},now).reason,'quote-overdue','a fresh check cannot extend the declared-delay event-age budget');
assert.equal(state.selectFreshness({...sample,sourceCheckedAt:now-40000,fetchedAt:now},now).stale,true,'fresh response cannot disguise overdue upstream check');
assert.equal(state.selectFreshness({...sample,recovery:true},now).stale,true);
assert.equal(state.selectFreshness({...sample,marketState:'CLOSED',checkIntervalMs:60000,sourceCheckedAt:now-46000},now).stale,false);
assert.equal(state.selectFreshness({...sample,marketState:'BREAK',quoteAt:now-96*60000},now).stale,true,'arbitrary old trades cannot hide behind a lunch break');
assert.match(q.changeBaseline.textContent,/较昨收基准 717.67/);assert.match(q.extRow.innerHTML,/较常规收盘 718.96/);assert.equal(q.pct.textContent,'-0.02%');assert.match(q.extRow.innerHTML,/-0.20%/);
q.d={...sample,priceSession:'PRE',ext:{pre:{price:717.54,change:-1.42,changePct:-.2}}};H.render(q);assert.match(q.extRow.innerHTML,/较常规收盘 718.96/);assert.doesNotMatch(q.extRow.innerHTML,/本交易日/,'PRE date is not guessed');
q.d={...sample,ext:{post:{price:717.54,change:-3.46,changePct:-.48}}};H.render(q);assert.match(q.extRow.innerHTML,/较来源基准 721.00/,'unknown base remains numerically explicit');
q.d={...sample,quoteAt:Date.parse('2026-09-04T21:00:00Z'),regularQuoteAt:Date.parse('2026-09-04T20:00:00Z'),gmtoff:-14400};H.render(q);assert.match(q.extRow.innerHTML,/较本交易日常规收盘 718.96/,'POST trading-day claim requires both timestamps');
q.d={...sample,slowFields:{daily30:{expired:true},week52Range:{refreshState:'queued'}}};H.updateQuoteMeta(q,now);assert.match((q.quoteDetails?.textContent||'')+(q.quoteAge?.textContent||'')+(q.sourceCheckAge?.textContent||''),/日K缓存待更新/);assert.match((q.quoteDetails?.textContent||'')+(q.quoteAge?.textContent||'')+(q.sourceCheckAge?.textContent||''),/52周范围排队更新中/);
env.fetch.push('market',{status:500,body:[]});await H.refresh(false);H.setCardCurrency('QQQ','CNY');assert.match(q.state.textContent,/拉取失败/);assert.equal(q.fetchStatus,'error');
env.fetch.push('market',{body:[{symbol:'QQQ',pending:true}]});await H.refresh(false);H.setCardCurrency('QQQ','USD');assert.match(q.state.textContent,/拉取失败/,'pending cannot clear prior failure');
env.fetch.push('market',{body:[sample]});await H.refresh(false);assert.equal(q.fetchStatus,'success');assert.equal(q.retryBtn.hidden,true);
env.fetch.push('market',{body:[{symbol:'QQQ',pending:true}]});await H.refresh(false);H.setCardCurrency('QQQ','CNY');assert.match(q.state.textContent,/等待更新/,'pending survives format-only render');
const deferred=env.fetch.push('market',{defer:true,body:[sample]});const pending=H.refresh(false);q.closeBtn.click();deferred.reject(new Error('obsolete connection'));await pending;await env.drain();H.tickClock();assert.equal(env.byId('updateAt').textContent,'自选为空');assert.equal(env.byId('session').textContent,'未选择标的');
let scroll;const target={scrollIntoView:opts=>scroll=opts};env.win.matchMedia=()=>({matches:true});state.scrollToCard(target);assert.equal(scroll.behavior,'instant');env.win.matchMedia=()=>({matches:false});state.scrollToCard(target);assert.equal(scroll.behavior,'smooth');
const closed={...sample,marketState:'CLOSED',pollAfterMs:70000};
assert.equal(state.pollingPolicy([closed],{mode:'economy',hidden:false}).marketMs,70000);
assert.equal(state.pollingPolicy([closed,{...sample,pollAfterMs:0}],{mode:'economy'}).marketMs,2000,'active market wins mixed list');
assert.equal(state.pollingPolicy([closed],{mode:'continuous',hidden:true}).marketMs,2000,'explicit continuous mode keeps background cadence');
assert.equal(state.pollingPolicy([{...closed,nextMarketTransitionAt:now+4000}],{now}).marketMs,4500,'server calendar boundary shortens closed cadence');
assert.equal(state.pollingPolicy([{...closed,nextMarketTransitionAt:now-1000}],{now}).marketMs,2000,'just-passed boundary refreshes promptly');
assert.equal(state.pollingPolicy([{...closed,nextMarketTransitionAt:now-180000}],{now}).marketMs,70000,'obsolete boundary does not cause permanent fast closed polling');
H.setRefreshMode('continuous');env.doc.hidden=true;assert.equal(H.refreshModeRef(),'continuous');H.setRefreshMode('economy');assert.equal(H.refreshModeRef(),'economy');assert.equal(env.sandbox.localStorage.getItem('qqq-refresh-mode'),'economy');
console.log('PASS v62 persistent request state, freshness/provider cadence, cancellation empty state, denominator labels, reduced motion and monitoring preference');
const hkNoon=Date.parse('2026-09-07T04:01:00Z');
assert.equal(state.selectFreshness({marketState:'BREAK',quoteAt:hkNoon-60*60000,sourceCheckedAt:hkNoon,sessionStartedAt:hkNoon-60000},hkNoon).stale,true,'Hong Kong stale morning trade is not hidden by lunch');
const cnNoon=Date.parse('2026-09-07T04:00:00Z');
const paused={marketState:'BREAK',quoteAt:cnNoon-30*60000,sessionStartedAt:cnNoon-30*60000,sourceCheckedAt:cnNoon-45000,pollAfterMs:2000};
assert.equal(state.selectFreshness(paused,cnNoon,{readIntervalMs:60000}).stale,false,'planned minute read cadence does not falsely mark morning-close source overdue');
assert.equal(state.selectFreshness({...paused,sourceCheckedAt:cnNoon-70000},cnNoon,{readIntervalMs:60000}).stale,true,'missing intended read still ages into stale');
