import {readSseEvent} from '../support/read-sse.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {once} from 'node:events';
import {createMacroMonitor} from '../../lib/macro-monitor.js';import {createMacroContext} from '../../lib/macro-context.js';import {createMacroCalendar} from '../../lib/providers/macro-calendar.js';import {createMacroNotifier} from '../../lib/macro-notify.js';import {createApplication} from '../../app.js';import {createTelemetry} from '../../log.mjs';import {createMacroFixture} from './macro-fixture.mjs';
const START=Date.parse('2026-09-11T08:00:00Z');const delay=ms=>new Promise(r=>setTimeout(r,ms));
function setup(options={}){let clock=START,news=[],calls=0,failed=false;const now=()=>clock;
 const context=createMacroContext({now,pollMs:30,readQuote:async symbol=>{calls++;if(failed)throw Object.assign(new Error('HTTP 429'),{retryAt:clock+120000});return {symbol,price:100+(clock-START)/60000,quoteAt:clock,sourceCheckedAt:clock,src:'test'};}});
 const calendar=createMacroCalendar({now});const macro={getMacro:async()=>({items:news,updatedAt:clock})};
 const monitor=createMacroMonitor({context,calendar,macro,now,tickMs:5,contextMs:30,newsMs:60,...options});
 return {monitor,context,calendar,now,calls:()=>calls,time:ms=>clock+=ms,news:rows=>news=rows,fail:()=>failed=true};}
const item=(title,t=START)=>({title,sourceText:title,t,topic:'原油',link:'https://example.test/'+encodeURIComponent(title),src:'测试来源'});
test('真实定时器：没有任何HTTP/SSE客户端时后台仍定时执行',async t=>{
 let count=0;const context={getContext:async()=>{count++;return {factors:[{price:1,status:'ready'}]};},snapshot:()=>({factors:[]}),exportState:()=>({}),restore(){}};
 const monitor=createMacroMonitor({context,calendar:{getCalendar:async()=>({status:'disabled'}),snapshot:()=>({})},macro:{getMacro:async()=>({items:[]})},tickMs:5,contextMs:20,newsMs:30});t.after(()=>monitor.stop());await monitor.start();await delay(85);assert.ok(count>=3,'backend timer must not need a browser');assert.equal(monitor.status().delivery.subscribers,0);});
test('重入与订阅退订不产生另一套采集；停止后不再读取',async()=>{const s=setup();await s.monitor.start();await s.monitor.settled();assert.equal(s.calls(),5);const off=s.monitor.subscribe(()=>{});for(let n=0;n<8;n++)s.monitor.runDue();await s.monitor.settled();assert.equal(s.calls(),5);off();s.time(60000);s.monitor.runDue();await s.monitor.settled();assert.equal(s.calls(),10);assert.equal(s.monitor.snapshot().context.comparison,'comparable');await s.monitor.stop();s.time(60000);s.monitor.runDue();await delay(20);assert.equal(s.calls(),10);});
test('持久化恢复来源采样和新闻，重启不是重新等15分钟',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'macro25-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const file=path.join(dir,'state.json');const a=setup({statePath:file});a.news([item('OPEC announces oil production cuts')]);await a.monitor.start();await a.monitor.settled();a.time(60000);a.monitor.runDue();await a.monitor.settled();await a.monitor.stop();const b=setup({statePath:file});b.time(60000);await b.monitor.start();await b.monitor.settled();assert.equal(b.monitor.snapshot().context.comparison,'comparable');assert.equal(b.monitor.snapshot().context.factors[0].quoteAt,START+60000);assert.ok(b.monitor.snapshot().news.items.length);assert.ok(b.monitor.status().restoredAt);await b.monitor.stop();});
test('损坏状态可启动但明确记录恢复失败，不制造历史采样',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'macro25-bad-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const file=path.join(dir,'state.json');await fs.writeFile(file,'{bad');const s=setup({statePath:file});await s.monitor.start();await s.monitor.settled();assert.match(s.monitor.status().persistence.loadError,/未恢复/);assert.equal(s.monitor.snapshot().context.factors[0].samples,1);await s.monitor.stop();});
test('全部因子429时仍独立更新新闻，不把失败采集标成成功',async()=>{const s=setup();s.fail();s.news([item('OPEC announces oil production cuts')]);await s.monitor.start();await s.monitor.settled();assert.equal(s.monitor.status().lanes.context.successAt,null);assert.match(s.monitor.status().lanes.context.error,/未取得/);assert.equal(s.monitor.snapshot().news.items.length,1);s.time(60000);s.monitor.runDue();await s.monitor.settled();assert.equal(s.calls(),5,'120秒限流未到不得重试');assert.equal(s.monitor.status().lanes.news.runs,2);await s.monitor.stop();});
test('发布前共识跨重启保留，发布后当前预期不覆盖真实捕获值',async()=>{let now=START;let actual='';const get=async()=>({status:200,body:JSON.stringify([{CalendarId:1,Country:'United States',Event:'Core Inflation Rate MoM',Reference:'Aug',Date:new Date(START+60000).toISOString(),DateSpan:0,Actual:actual,Forecast:actual?'0.2%':'0.3%',Unit:'%'}])});const a=createMacroCalendar({key:'private-key',now:()=>now,httpsGet:get});await a.getCalendar();const b=createMacroCalendar({key:'private-key',now:()=>now,httpsGet:get});b.restore(a.exportState());now+=120000;actual='0.2%';await b.getCalendar();assert.equal(b.snapshot().items[0].surprise,-.1);assert.equal(b.snapshot().items[0].consensusCapturedAt,START);assert.ok(!JSON.stringify(b.exportState()).includes('private-key'));});
test('外部通知只发送新增重点事件，重试遵守429且不重复发送',async()=>{let sends=0;const s=setup({notify:async()=>{sends++;if(sends===1)throw Object.assign(new Error('429'),{retryAt:START+180000});}});s.news([item('background market commentary')]);await s.monitor.start();await s.monitor.settled();s.time(60000);s.news([item('OPEC announces oil production cuts',s.now())]);s.monitor.runDue();await s.monitor.settled();await delay(15);assert.equal(sends,1);s.time(60000);s.monitor.runDue();await s.monitor.settled();assert.equal(sends,1);s.time(60000);s.monitor.runDue();await s.monitor.settled();await delay(15);assert.equal(sends,2);s.time(60000);s.monitor.runDue();await s.monitor.settled();await delay(15);assert.equal(sends,2);assert.equal(s.monitor.status().delivery.pending,0);await s.monitor.stop();});
test('可选Webhook只接受HTTPS，权限只出现在服务端请求头',async()=>{assert.throws(()=>createMacroNotifier({url:'http://example.test'}));let got;const send=createMacroNotifier({url:'https://example.test/notify',token:'secret-test',fetchImpl:async(u,o)=>{got=o;return new Response('',{status:204});}});await assert.rejects(send({id:1})); // A malformed mocked 204 body must not be swallowed.
 const ok=createMacroNotifier({url:'https://example.test/notify',token:'secret-test',fetchImpl:async(u,o)=>{got=o;return new Response(null,{status:204});}});await ok({id:2});assert.equal(got.headers.Authorization,'Bearer secret-test');assert.ok(!got.body.includes('secret-test'));assert.equal(got.redirect,'error');});
test('生产HTTP：零页面启动采集、SSE快照、断线后台继续、重新连接拿新快照',async t=>{const f=createMacroFixture();const app=createApplication({env:{HISTORY_BACKGROUND_ENABLED:'0',HISTORY_STATE_PATH:'',PORT:0,MACRO_STATE_PATH:'',TE_API_KEY:'fixture-key'},now:f.now,upstream:f.upstream,telemetry:createTelemetry()});t.after(()=>app.stop());app.start();await once(app.httpServer,'listening');await app.services.macroMonitor.settled();const base='http://127.0.0.1:'+app.httpServer.address().port;
 assert.ok(f.calls.length>0);assert.ok(app.services.macroMonitor.snapshot().news.items.length>3);const c=new AbortController(),r=await fetch(base+'/api/macro/stream',{signal:c.signal});assert.equal(r.headers.get('content-type'),'text/event-stream; charset=utf-8');const reader=r.body.getReader();const text=await readSseEvent(reader,{event:'macro'});assert.match(text,/event: macro/);assert.ok(!text.includes('fixture-key'));c.abort();await reader.cancel().catch(()=>{});await delay(10);
 const first=app.services.macroMonitor.status().lanes.context.runs;f.advance();app.services.macroMonitor.runDue();await app.services.macroMonitor.settled();assert.ok(app.services.macroMonitor.status().lanes.context.runs>first);assert.equal(app.services.macroMonitor.status().delivery.subscribers,0);const data=await(await fetch(base+'/api/macro/snapshot')).json();assert.equal(data.context.comparison,'comparable');assert.equal(data.context.calendar.items[0].surprise,-.1);assert.ok(data.monitor.running);const before=f.calls.length;await fetch(base+'/api/macro');await fetch(base+'/api/macro/context');await fetch(base+'/api/macro/status');assert.equal(f.calls.length,before,'HTTP readers must not launch extra collectors');
});
