import test from 'node:test';import assert from 'node:assert/strict';
import {createMacroContext,macroIndexQuote,MACRO_FACTORS} from '../../lib/macro-context.js';
const start=Date.parse('2026-09-11T13:00:00Z');
function setup(){let time=start,calls=0,mode='ok',source='source';const prices=Object.fromEntries(MACRO_FACTORS.map(f=>[f.symbol,100]));const svc=createMacroContext({now:()=>time,readQuote:async symbol=>{calls++;if(mode==='429')throw Object.assign(new Error('rate limited'),{retryAt:time+120000});return {symbol,price:prices[symbol],quoteAt:mode==='no-time'?null:mode==='old'?time-20*60000:time,sourceCheckedAt:time,src:source,currency:'USD'};}});return {svc,prices,time:n=>time=n,mode:n=>mode=n,source:n=>source=n,calls:()=>calls};}
test('construction, snapshot and folded UI do not schedule upstream work; concurrent context calls share a batch',async()=>{const s=setup();s.svc.snapshot();assert.equal(s.calls(),0);await Promise.all([s.svc.getContext(),s.svc.getContext()]);assert.equal(s.calls(),5);await s.svc.getContext();assert.equal(s.calls(),5);});
test('startup waits for a real same-window anchor, never synthesizes day returns',async()=>{const s=setup();let d=await s.svc.getContext();assert.equal(d.comparison,'waiting');assert.ok(d.factors.every(f=>f.change===null));s.time(start+15*60000);s.prices['CL00Y.FUT']=98;s.prices['NQ00Y.FUT']=101;d=await s.svc.getContext();assert.equal(d.comparison,'comparable');assert.equal(d.factors.find(f=>f.id==='wti').change,-2);assert.ok(d.observations[0].includes('不能确认资金'));});
test('no source trade time or old source time cannot be refreshed by an HTTP success',async()=>{for(const mode of ['no-time','old']){const s=setup();s.mode(mode);await s.svc.getContext();s.time(start+15*60000);const d=await s.svc.getContext();assert.equal(d.comparison,'waiting');assert.ok(d.factors.every(f=>!f.fresh&&f.change===null));}});
test('source identity changes reset samples rather than splice series',async()=>{const s=setup();await s.svc.getContext();s.time(start+15*60000);s.source('different');const d=await s.svc.getContext();assert.equal(d.comparison,'waiting');assert.ok(d.factors.every(f=>f.samples===1));});
test('429 respects retryAt and cached quote remains old, with an error',async()=>{const s=setup();await s.svc.getContext();s.time(start+31000);s.mode('429');let d=await s.svc.getContext();assert.ok(d.factors.every(f=>f.status==='error'&&f.quoteAt===start));s.time(start+61000);await s.svc.getContext();assert.equal(s.calls(),10);});
test('closing stops reads and restart restores normal service',async()=>{const s=setup();s.svc.close();await s.svc.getContext();assert.equal(s.calls(),0);s.svc.reopen();await s.svc.getContext();assert.equal(s.calls(),5);});
test('index quotes preserve exact identity and raw units, reject mismatched and missing prices',()=>{assert.throws(()=>macroIndexQuote({meta:{symbol:'OTHER',instrumentType:'INDEX',regularMarketPrice:4}},'^TNX'));assert.throws(()=>macroIndexQuote({meta:{symbol:'^TNX',instrumentType:'INDEX',regularMarketPrice:null}},'^TNX'));const q=macroIndexQuote({meta:{symbol:'^TNX',instrumentType:'INDEX',regularMarketPrice:4.1,regularMarketTime:start/1000}},'^TNX',start);assert.equal(q.price,4.1);assert.equal(q.quoteAt,start);});
test('declared delayed feed cannot enter synchronous comparisons just because it reports a recent timestamp',async()=>{let time=start;const s=createMacroContext({now:()=>time,readQuote:async symbol=>({symbol,price:100,quoteAt:time,feedDelayMinutes:15})});await s.getContext();time+=15*60000;const d=await s.getContext();assert.equal(d.comparison,'waiting');assert.ok(d.factors.every(f=>!f.fresh&&f.samples===0));});
