import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {makeEl} from '../_harness.mjs';import {safeUrl} from '../../lib/context-values.js';
const NOW=Date.parse('2026-09-21T12:00:00Z'),DAY=864e5;
function env(module){const events={},doc={activeElement:null,hidden:false,getElementById:()=>null,createElement(tag){const el=makeEl(tag);el.tagName=tag.toUpperCase();el.ownerDocument=doc;el.insertBefore=(child,before)=>{child.remove();const i=el.children.indexOf(before);if(i<0)el.appendChild(child);else{el.children.splice(i,0,child);child.parentNode=el;}return child;};return el;}};
 const window={PANEL_FORMAT:{esc:String,fmtTime8:String},EventSource:class{addEventListener(key,fn){events[key]=fn;}close(){}},addEventListener(){}};vm.runInNewContext(fs.readFileSync(new URL('../../public/modules/'+module,import.meta.url),'utf8'),{window,document:doc,Date,JSON,URL,setTimeout,clearTimeout});return {window,doc,events};}
const item=(title,t=NOW-1000)=>({title,t,src:'Reuters',link:'https://www.reuters.com/article/'+title});
test('v95 related-news render drops old/future records and removes a cached row when it crosses seven days',()=>{let now=NOW;const {window,doc}=env('panel-news-controller.js');const c=window.PANEL_NEWS_CONTROLLER.createNewsController({now:()=>now,network:{},client:{safeURL:safeUrl},getWatchlist:()=>[],getCards:()=>[]}),q={newshead:doc.createElement('summary'),newslist:doc.createElement('div')};
 const rows=[item('boundary',NOW-7*DAY+1),item('may',Date.parse('2026-05-01')),item('future',NOW+1)];c.renderNews(q,rows);assert.equal(q.newslist.children.length,1);assert.match(q.newslist.children[0].innerHTML,/boundary/);now+=2;c.renderNews(q,rows.slice(0,2),{stale:true});assert.ok(q.newslist.children[0].classList.contains('newsempty'));assert.ok(!q.newslist.children.some(x=>x.innerHTML.includes('boundary')));
});
test('v95 an empty failure response clears old browser items instead of restoring them',async()=>{const {window,doc}=env('panel-news-controller.js');const q={newshead:doc.createElement('summary'),newslist:doc.createElement('div')};let calls=0;const c=window.PANEL_NEWS_CONTROLLER.createNewsController({now:()=>NOW,network:{request:async()=>({ok:true,json:async()=>({AAOI:++calls===1?[item('first')]:[]}),headers:{}})},client:{safeURL:safeUrl,decodeNewsMetadata:()=>({AAOI:calls===1?{}:{stale:true,error:'outage'}})},getWatchlist:()=>['AAOI'],getCards:()=>[['AAOI',q]]});
 await c.refreshNews();assert.match(q.newslist.children[0].innerHTML,/first/);await c.refreshNews();assert.ok(q.newslist.children[0].classList.contains('newsempty'));
});
test('v95 macro SSE rendering and wall-clock ticks prune stale news during a source outage',()=>{let now=NOW;const {window,doc,events}=env('panel-macro-controller.js'),box=doc.createElement('div');const c=window.PANEL_MACRO_CONTROLLER.createMacroController({now:()=>now,document:doc,network:{},client:{safeURL:safeUrl},box,filters:doc.createElement('div'),status:doc.createElement('div'),retry:doc.createElement('button')});
 events.macro({data:JSON.stringify({revision:1,news:{items:[{...item('boundary',NOW-7*DAY+1),assessment:{importance:'focus',status:'watch'}},item('old',NOW-8*DAY)],stale:true},context:{factors:[]},monitor:{enabled:true}})});assert.equal(c.items().length,1);assert.equal(box.children[0].className,'macro-event');now+=2;c.tick();assert.equal(c.items().length,0);assert.ok(box.children[0].classList.contains('newsempty'));
});
test('v95 related-news clock tick removes an expired row without another network request',async()=>{
 let now=NOW,calls=0;const {window,doc}=env('panel-news-controller.js'),q={newshead:doc.createElement('summary'),newslist:doc.createElement('div')};
 const c=window.PANEL_NEWS_CONTROLLER.createNewsController({now:()=>now,network:{request:async()=>{calls++;return {ok:true,json:async()=>({AAOI:[item('boundary',NOW-7*DAY+1)]}),headers:{}};}},client:{safeURL:safeUrl,decodeNewsMetadata:()=>({})},getWatchlist:()=>['AAOI'],getCards:()=>[['AAOI',q]]});
 await c.refreshNews();assert.match(q.newslist.children[0].innerHTML,/boundary/);now+=2;c.tick();assert.equal(calls,1);assert.ok(q.newslist.children[0].classList.contains('newsempty'));
});
