import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

// Keep source modules independently testable. Only the shipped script is joined.
export const STATIC_INPUTS=Object.freeze([
  'public/modules/panel-client.js',
  'public/modules/panel-currency.js',
  'public/modules/panel-chart.js',
  'public/modules/panel-timeframes.js',
  'public/modules/panel-history-store.js',
  'public/modules/panel-sample-store.js',
  'public/modules/panel-chart-engine.js',
  'public/modules/panel-scheduler.js',
  'public/modules/panel-network.js',
  'public/modules/panel-watchlist-sync.js',
  'public/modules/panel-admin.js',
  'public/modules/panel-state.js',
  'public/modules/panel-utils.js',
  'public/modules/panel-format.js',
  'public/modules/panel-chart-controller.js',
  'public/modules/panel-fundamentals.js',
  'public/modules/panel-detail.js',
  'public/modules/panel-chart-detail.js',
  'public/modules/panel-card-view.js',
  'public/modules/panel-search-controller.js',
  'public/modules/panel-market-directory.js',
  'public/modules/panel-news-controller.js',
  'public/modules/panel-macro-context.js',
  'public/modules/panel-macro-controller.js',
  'public/modules/panel-market-store.js',
  'public/modules/panel-live-store.js',
  'public/app.js',
]);

// Most references are inside factories and may point forward. These two
// modules dereference other globals immediately, before app.js runs.
const eagerDependencies={
  'public/modules/panel-utils.js':['PANEL_CLIENT','PANEL_CURRENCY','PANEL_CHART','PANEL_CHART_ENGINE','PANEL_SCHEDULER','PANEL_NETWORK','PANEL_STATE'],
  'public/modules/panel-fundamentals.js':['PANEL_FORMAT'],
};
export function validateStaticDependencies(sources) {
  const providers=new Map();
  sources.forEach(({file,source},index)=>{
    for(const [,name] of source.matchAll(/\bwindow\.(PANEL_[A-Z_]+)\s*=(?!=)/g)){
      if(providers.has(name))throw new Error('Duplicate browser module: '+name+' in '+file);
      providers.set(name,index);
    }
  });
  sources.forEach(({file,source},index)=>{
    for(const [,name] of source.matchAll(/\bwindow\.(PANEL_[A-Z_]+)\b/g))if(!providers.has(name))throw new Error('Missing browser module: '+name+' in '+file);
    for(const name of eagerDependencies[file]||[])if(providers.get(name)>=index)throw new Error('Browser module order: '+name+' must precede '+file);
  });
  if(sources.at(-1)?.file!=='public/app.js')throw new Error('Browser composition must run last');
}

export function buildStatic(root,{check=false}={}) {
  let code='/* Generated by scripts/build-static.mjs; edit original modules. */\n';
  const files=[],sources=[];
  for(const file of STATIC_INPUTS) {
    const input=path.join(root,file),stat=fs.lstatSync(input);
    if(!stat.isFile()||stat.isSymbolicLink())throw new Error('Static input must be a regular file: '+file);
    const source=fs.readFileSync(input,'utf8');
    sources.push({file,source});
    code+='\n;/* '+file+' */\n';
    const startOffset=code.length;
    code+=source;
    files.push({path:file,startOffset,endOffset:code.length});
    code+='\n;\n';
  }
  validateStaticDependencies(sources);
  const outputs={'public/panel.bundle.js':code,'public/panel.bundle.layout.json':JSON.stringify({version:1,encoding:'utf16',files},null,2)+'\n'};
  for(const [file,content] of Object.entries(outputs)) {
    const target=path.join(root,file);
    const stat=fs.existsSync(target)?fs.lstatSync(target):null;
    if(stat && (!stat.isFile()||stat.isSymbolicLink()))throw new Error('Static output must be a regular file: '+file);
    const actual=stat?fs.readFileSync(target,'utf8'):null;
    if(check && actual!==content)throw new Error('Static bundle is stale: '+file+'; run node scripts/build-static.mjs before verification');
    if(!check && actual!==content)fs.writeFileSync(target,content,{mode:0o644});
  }
  return {inputs:files.length,bytes:Buffer.byteLength(code),checked:check};
}

if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)) {
  try {
    const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
    console.log('Static assets:',JSON.stringify(buildStatic(root,{check:process.argv.includes('--check')})));
  } catch(error) {console.error(error.message);process.exitCode=1;}
}
